// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2);
}

export function GetCompanies() {
  return window['go']['main']['App']['GetCompanies']();
}

export function GetReports() {
  return window['go']['main']['App']['GetReports']();
}

export function GetUsersForCompany(arg1) {
  return window['go']['main']['App']['GetUsersForCompany'](arg1);
}

export function SendEmail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3, arg4);
}
