// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateReport(arg1:string,arg2:number):Promise<string>;

export function GetCompanies():Promise<Array<main.Company>>;

export function GetReports():Promise<Array<main.ReportInfo>>;

export function GetUsersForCompany(arg1:string):Promise<Array<string>>;

export function SendEmail(arg1:Array<string>,arg2:Array<string>,arg3:string,arg4:string):Promise<void>;
